[package]
name = "secure-wipe"
version = "0.1.0"
authors = ["alake <g4titan1@gmail.com>"]
edition = "2021"

[dependencies]
env_logger = "0.11.6"
error = "0.1.9"
log = "0.4.22"
rand = "0.8.5"
thiserror = "2.0.9"
